// Generated by CoffeeScript 1.6.2
(function() {
  var angularModules;

  angularModules = [];

  this.APP = angular.module('matersApp', angularModules);

  this.AppController = function($scope) {
    $scope.hideClosed = false;
    $scope.stateFilter = '';
    $scope.clientFilterText = '';
    $scope.keywordFilterText = '';
    return $scope.$watch('hideClosed', function(value) {
      if (value === true) {
        return $scope.stateFilter = 'open';
      } else {
        return $scope.stateFilter = '';
      }
    });
  };

  this.MatterListController = function($scope) {
    return $scope.matters = _seedData;
  };

}).call(this);
