// Generated by CoffeeScript 1.6.2
(function() {
  var angularModules;

  angularModules = [];

  this.APP = angular.module('matersApp', angularModules);

  this.AppController = function($scope) {
    return $scope.hideClosed = false;
  };

  this.MatterListController = function($scope) {
    return $scope.matters = _seedData;
  };

}).call(this);
